version: '3.8'

services:
  product-service:
    build: 
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/product_db
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - postgres

  price-service:
    build:
      context: ./price-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - product-service

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=product_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
